name: Jdy98p
favicon: null
layout_spectrum: 0.59079
typography_spectrum: 0.26854
title: Test Grid Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.9409489503595978
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
